# Exercice 3: Using `pandas`

## Question 1. Import `pandas` module and make it usable through the shortcut `pd`

In [8]:
import pandas as pd

## Question 2. Load the third table of webpage https://en.wikipedia.org/wiki/List_of_cities_in_Japan as a pandas dataframe

In [9]:
tables = pd.read_html('https://en.wikipedia.org/wiki/List_of_cities_in_Japan')
df = tables[2]

## Question 3. Inspect the dataframe

In [10]:
df

,0,1,2,3,4,5,6,7
0,City (Special Ward),Japanese,Prefecture,Population,Area,Density,Founded,Homepage
1,Nagoya,名古屋市,Aichi,2283289,326.45,6860,1889-10-01,[1]
2,Toyohashi,豊橋市,Aichi,377045,261.35,1443,1906-08-01,[2]
3,Okazaki,岡崎市,Aichi,371380,387.24,959,1916-07-01,[3]
4,Ichinomiya,一宮市,Aichi,375939,113.91,3300,1921-09-01,[4]
5,Seto,瀬戸市,Aichi,132311,111.61,1185,1929-10-01,[5]
6,Handa,半田市,Aichi,117927,47.24,2496,1937-10-01,[6]
7,Kasugai,春日井市,Aichi,300713,92.71,3244,1943-06-01,[7]
8,Toyokawa,豊川市,Aichi,161595,150.71,1072,1943-06-01,[8]
9,Tsushima,津島市,Aichi,65646,25.08,2617,1947-03-01,[9]
10,Hekinan,碧南市,Aichi,73024,35.86,2036,1948-04-05,[10]
11,Kariya,刈谷市,Aichi,145117,50.45,2876,1950-04-01,[11]
12,Toyota,豊田市,Aichi,420286,918.47,458,1951-03-01,[12]
13,AnjoAnjō,安城市,Aichi,176046,86.01,2047,1952-05-05,[13]
14,Nishio,西尾市,Aichi,106643,75.78,1407,1953-12-15,[14]
15,GamagoriGamagōri,蒲郡市,Aichi,82264,56.81,1448,1954-04-01,[15]
16,Inuyama,犬山市,Aichi,75304,74.97,1004,1954-04-01,[16]
17,Tokoname,常滑市,Aichi,52837,55.63,950,1954-04-01,[17]
18,KonanKōnan,江南市,Aichi,100064,30.17,3317,1954-06-01,[18]
19,Komaki,小牧市,Aichi,149060,62.82,2373,1955-01-01,[19]
20,Inazawa,稲沢市,Aichi,137475,79.30,1734,1958-11-01,[20]
21,TokaiTōkai,東海市,Aichi,106708,43.36,2461,1969-04-01,[21]
22,ObuŌbu,大府市,Aichi,83097,33.68,2467,1970-09-01,[22]
23,Chita,知多市,Aichi,84782,45.43,1866,1970-09-01,[23]
24,ChiryuChiryū,知立市,Aichi,68216,16.34,4175,1970-12-01,[24]
25,Owariasahi,尾張旭市,Aichi,79197,21.03,3766,1970-12-01,[25]
26,Takahama,高浜市,Aichi,43467,13.00,3344,1970-12-01,[26]
27,Iwakura,岩倉市,Aichi,48042,10.49,4580,1971-12-01,[27]
28,Toyoake,豊明市,Aichi,69124,23.18,2982,1972-08-01,[28]
29,Nisshin,日進市,Aichi,80921,34.90,2319,1994-10-01,[29]
...,...,...,...,...,...,...,...,...
786,Obanazawa,尾花沢市,Yamagata,19937,372.32,53.5,1959-04-10,[785]
787,Nan'yoNan'yō,南陽市,Yamagata,34542,160.70,215,1967-04-01,[786]
788,Tsuruoka,鶴岡市,Yamagata,140097,1311.51,107,2005-10-01,[787]
789,Sakata,酒田市,Yamagata,114964,602.79,191,2005-11-01,[788]
790,Ube,宇部市,Yamaguchi,176370,287.69,613,1921-11-01,[789]
791,HofuHōfu,防府市,Yamaguchi,116393,188.59,617,1936-08-25,[790]
792,Kudamatsu,下松市,Yamaguchi,54026,89.36,605,1939-11-03,[791]
793,ShunanShūnan,周南市,Yamaguchi,150299,656.25,229,2003-04-21,[792]
794,Hikari,光市,Yamaguchi,53274,91.94,579,2004-10-04,[793]
795,Shimonoseki,下関市,Yamaguchi,286073,716.06,400,2005-02-13,[794]
796,Yanai,柳井市,Yamaguchi,35438,139.90,253,2005-02-21,[795]
797,Hagi,萩市,Yamaguchi,55831,698.87,79.9,2005-03-06,[796]
798,Nagato,長門市,Yamaguchi,39825,357.92,111,2005-03-22,[797]
799,San'yo-OnodaSan'yō-Onoda,山陽小野田市,Yamaguchi,65523,132.99,493,2005-03-22,[798]
800,Yamaguchi,山口市,Yamaguchi,192008,730.23,263,2005-10-01,[799]
801,Iwakuni,岩国市,Yamaguchi,146885,872.71,168,2006-03-20,[800]
802,Mine,美祢市,Yamaguchi,17355,228.25,76.0,2008-03-21,[801]
803,KofuKōfu,甲府市,Yamanashi,199374,212.41,939,1889-07-01,[802]
804,Fujiyoshida,富士吉田市,Yamanashi,51879,121.83,426,1951-03-20,[803]
805,Tsuru,都留市,Yamanashi,34439,161.58,213,1954-04-29,[804]
806,OtsukiŌtsuki,大月市,Yamanashi,29869,280.30,107,1954-08-08,[805]
807,Nirasaki,韮崎市,Yamanashi,33539,143.73,233,1954-10-10,[806]
808,Minami-Alps,南アルプス市,Yamanashi,72295,264.06,274,2003-04-01,[807]
809,Kai,甲斐市,Yamanashi,74077,71.94,1030,2004-09-01,[808]
810,Fuefuki,笛吹市,Yamanashi,71184,201.92,353,2004-10-12,[809]
811,Hokuto,北杜市,Yamanashi,47754,602.89,79.2,2004-11-01,[810]
812,Uenohara,上野原市,Yamanashi,28295,170.65,166,2005-02-13,[811]
813,Yamanashi,山梨市,Yamanashi,38202,289.87,132,2005-03-22,[812]
814,KoshuKōshū,甲州市,Yamanashi,35072,264.01,133,2005-11-01,[813]
815,ChuoChūō,中央市,Yamanashi,31875,31.81,1002,2006-02-20,[814]

## Question 4. Inspect the first line of `df` [hint: use `iloc` method]

In [11]:
df.iloc[0]

0    City (Special Ward)
1               Japanese
2             Prefecture
3             Population
4                   Area
5                Density
6                Founded
7               Homepage
Name: 0, dtype: object

## Question 5. Use the first line to assign column names and then drop it

In [12]:
df.columns = df.iloc[0]
df.drop(0, inplace=True)#Replace dots with code

## Question 6. List the column names and change data types

In [13]:
list(df)
df['Population'] = pd.to_numeric(df['Population'])
df['Area'] = pd.to_numeric(df['Area'])
df['Density'] = pd.to_numeric(df['Density'])
df['Founded'] = pd.to_datetime(...)#Replace dots with code

TypeError: <class 'ellipsis'> is not convertible to datetime

## Question 7. Drop the `homepage` column

In [ ]:
df.drop('Homepage', axis=1, inplace=True) #Replace dots with code

## Question 8. Count the number of lines in `df`

In [ ]:
len(...) #Replace dots with code

## Question 9. Count how data are *not* missing for each column [hint: use `count` method]

In [9]:
...#Replace dots with code

0
City (Special Ward)    815
Japanese               815
Prefecture             815
Population             811
Area                   815
Density                811
Founded                814
dtype: int64

## Question 10. Drop missing data [hint: use `dropna` method]

In [10]:
df.dropna(inplace=True)

## Question 11. Compute the mean, median, quartiles, min and max values of `Population`, `Area` and `Density` [hint: use `describe` method]

In [11]:
df.describe()

0        Population         Area       Density
count  8.100000e+02   810.000000    810.000000
mean   1.423383e+05   261.662111   1831.090012
std    2.529803e+05   281.139001   3210.514702
min    4.259000e+03     5.100000     13.700000
25%    4.346925e+04    63.305000    191.750000
50%    6.954150e+04   160.290000    464.055000
75%    1.324378e+05   367.995000   1630.250000
max    3.697894e+06  2177.670000  20097.000000

## Question 12. Use `describe` on qualitative variables `City`, `Japanese` and `Prefecture`

In [12]:
quali = ['City (Special Ward)', 'Japanese', 'Prefecture']
df[quali].describe() #Replace dots with code

0      City (Special Ward) Japanese Prefecture
count                  810      810        810
unique                 797      808         47
top                Miyoshi      伊達市      Tokyo
freq                     3        2         49

## Question 13. Group data by `Prefecture` and compute the agregate population

In [13]:
df.groupby(...).sum()[...] #Replace dots with code

Prefecture
Aichi         6879793.0
Akita         1007706.0
Aomori        1076881.0
Chiba         5815300.0
Ehime         1307869.0
Fukui          709075.0
Fukuoka       4377584.0
Fukushima     1622217.0
Gifu          1774140.0
Gunma         1656829.0
Hiroshima     2690096.0
Hokkaidō      4440652.0
Hyōgo         5320852.0
Ibaraki       2685103.0
Ishikawa      1016763.0
Iwate         1099710.0
Kagawa         844590.0
Kagoshima     1518850.0
Kanagawa      8672024.0
Kumamoto      1411334.0
Kyoto         2506147.0
Kōchi          628504.0
Mie           1635789.0
Miyagi        1909824.0
Miyazaki       895302.0
Nagano        1704615.0
Nagasaki      1290403.0
Nara          1109746.0
Niigata       2276113.0
Okayama       1829322.0
Okinawa       1066034.0
Osaka         8664108.0
Saga           706460.0
Saitama       6405960.0
Shiga         1262951.0
Shimane        607112.0
Shizuoka      3465824.0
Tochigi       1657073.0
Tokushima      597188.0
Tokyo        12691476.0
Tottori        436816.0
Toyama        1009547.0
Wakayama       785253.0
Yamagata       942289.0
Yamaguchi     1389300.0
Yamanashi      747854.0
Ōita          1145641.0
Name: Population, dtype: float64

## Question 14. Sort by descending order of agregate population number

In [14]:
df.groupby('Prefecture').sum()['Population'].sort_values(ascending=...) #Replace dots with code

Prefecture
Tokyo        12691476.0
Kanagawa      8672024.0
Osaka         8664108.0
Aichi         6879793.0
Saitama       6405960.0
Chiba         5815300.0
Hyōgo         5320852.0
Hokkaidō      4440652.0
Fukuoka       4377584.0
Shizuoka      3465824.0
Hiroshima     2690096.0
Ibaraki       2685103.0
Kyoto         2506147.0
Niigata       2276113.0
Miyagi        1909824.0
Okayama       1829322.0
Gifu          1774140.0
Nagano        1704615.0
Tochigi       1657073.0
Gunma         1656829.0
Mie           1635789.0
Fukushima     1622217.0
Kagoshima     1518850.0
Kumamoto      1411334.0
Yamaguchi     1389300.0
Ehime         1307869.0
Nagasaki      1290403.0
Shiga         1262951.0
Ōita          1145641.0
Nara          1109746.0
Iwate         1099710.0
Aomori        1076881.0
Okinawa       1066034.0
Ishikawa      1016763.0
Toyama        1009547.0
Akita         1007706.0
Yamagata       942289.0
Miyazaki       895302.0
Kagawa         844590.0
Wakayama       785253.0
Yamanashi      747854.0
Fukui          709075.0
Saga           706460.0
Kōchi          628504.0
Shimane        607112.0
Tokushima      597188.0
Tottori        436816.0
Name: Population, dtype: float64